### ISSUE TITLE
server crashes on first page load

### ISSUE THREAD

**Issue by runn-vermel** [GeneralElectric/grunt-dep-serve#4]
Windows 10, Surface pro4:

After launching the server successfully with grunt depserve, the server crashes once it gets the first request:

Fatal error: connect EADDRNOTAVAIL 0.0.0.0:8080

**Comment by misjob** [comment]
The problem is most likely the proxy on 0.0.0.0
Changing "0.0.0.0" to "127.0.0.1" or "localhost" fixes the problem
Have not tested if it brakes the proxy "magic"

**Comment by murone** [comment]
This issue still exists. Have to update the npm package every time I pull a new repo depending on this or do an npm update. 

Is there any case where 0.0.0.0 actually works?

**Comment by mdwragg** [comment]
Hi @murone , do you know how to make it work? Can you please submit a Pull Request if so?

Thanks!

**Comment by murone** [comment]
@mdwragg I can get it running for me, but i'm not sure if i'm using the proxy functionality referred to in the ReadMe, as I don't fully understand it. To @misjob 's point, not sure if switching it will break that "magic" or not. 

Happy to submit...just want to make sure someone will be properly vetting my solution so I don't break an important feature for a ton of people!

**Comment by mdwragg** [comment]
@murone - yep, we can test that :)

**Comment by mdwragg** [comment]
(nice to meet you, by the way!)
